// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Account struct {
	ID          int64
	Username    string
	DisplayName sql.NullString
	PrivateKey  sql.NullString
	PublicKey   sql.NullString
}
