// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID          int64
	Username    string
	Domain      sql.NullString
	DisplayName sql.NullString
	PrivateKey  sql.NullString
	PublicKey   sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Status struct {
	ID        int64
	AccountID int64
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
