// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64
	Username      string
	Domain        sql.NullString
	DisplayName   sql.NullString
	PrivateKey    string
	PublicKey     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ActivityPubID sql.NullString
}

type Status struct {
	ID        int64
	AccountID int64
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
